# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'litter-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for litter-swift
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1'
    pod 'KeyboardHideManager', '~> 1.0'
    pod 'SDCAlertView', '~> 7.1'
    pod ‘OHHTTPStubs/Swift’




  target 'litter-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'litter-swiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
